apiVersion: v1
kind: ServiceAccount
metadata:
  name: token-api
  namespace: token
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::REPLACE_ACCOUNT_ID:role/token-api-role
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: token-worker
  namespace: token
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::REPLACE_ACCOUNT_ID:role/token-worker-role
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: token-console
  namespace: token
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::REPLACE_ACCOUNT_ID:role/token-console-role
